Fix reading the wrong magazine property II $dto->magazine seems to be null relatively often, so switch to the already used $dto->post->magazine
Fixes this error:
> ERROR: php: Warning: Attempt to read property "apId" on null

Introduced in #1636